apiVersion: apps/v1 # Uses the stable Kubernetes API for workloads like Deployments
kind: Deployment # creating a Deployment Which Manages the Pod
metadata:
  name: boardgame-deployment # Unique name of this Deployment in the namespace
spec:
  selector:
    matchlabels:
      app: boardgame  # This tells the Deployment: “I manage Pods that have the label app=boardgame”
  replicas: 2 # Number of replicas that will be created for this deployment
  template: # This is the exact definition of the Pods that will be created.
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: adijaiswal/boardshack:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: boardgame-ssvc
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: NodePort # type of the service.
